Repository SolsticeOfTheWinter/Goob-Station-butEVIL, pull requests merged in 2025-03, with the labels that each got.

#2 some tweaks
  Resources/Locale/en-US/_Goobstation/undetermined-items/blueshield-undetermined.ftl
  Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/_Goobstation/Catalog/undetermined_item_sets.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/armour.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Ammunition/Magazines/energy_speedloaders.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/_Goobstation/Loadouts/loadout_groups.yml
  Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
Labels: Changes: No C#, size/S

#3 further work
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/_Goobstation/Catalog/Fills/Items/firstaidkit.yml
  Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/Ears/headsets_alt.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Ammunition/Boxes/shotgun.yml
  Resources/Prototypes/_Goobstation/Loadouts/role_loadouts.yml
  Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
Labels: size/M, S: Untriaged, Changes: No C#

#4 another pr
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_Goobstation/Catalog/Fills/Belt/belts.yml
  Resources/Prototypes/_Goobstation/Catalog/Fills/Items/firstaidkit.yml
  Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Specific/Medical/hypospray.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Ammunition/Magazines/energy_speedloaders.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/_Goobstation/Entities/Specific/Medical/medkits.yml
  Resources/Prototypes/_Goobstation/Entities/Specific/bso.yml
  Resources/Prototypes/_Goobstation/Entities/Specific/syndicate.yml
  Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/medical.yml
  Resources/Prototypes/_Goobstation/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/_Goobstation/Recipes/Lathes/security.yml
  Resources/Prototypes/_Goobstation/Roles/Jobs/Command/blueshield_officer.yml
  Resources/Textures/_Goobstation/Objects/Specific/Medical/cartridge.rsi/cartridge-saline.png
  Resources/Textures/_Goobstation/Objects/Specific/Medical/cartridge.rsi/meta.json
  Resources/Textures/_Goobstation/Objects/Specific/Medical/firstaidkits.rsi/bsokit-ipc-inhand-left.png
  Resources/Textures/_Goobstation/Objects/Specific/Medical/firstaidkits.rsi/bsokit-ipc-inhand-right.png
  Resources/Textures/_Goobstation/Objects/Specific/Medical/firstaidkits.rsi/bsokit-ipc.png
  Resources/Textures/_Goobstation/Objects/Specific/Medical/firstaidkits.rsi/meta.json
Labels: size/M, S: Untriaged, Changes: No C#, Changes: Sprites

#5 fix linter, rebalance suits, buff greatshield, funny cigs
  Resources/Prototypes/_Goobstation/Catalog/Fills/Lockers/suit_storage.yml
  Resources/Prototypes/_Goobstation/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Consumable/Cigarettes/cigarette.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Consumable/Cigarettes/packs.yml
  Resources/Prototypes/_Goobstation/Entities/Objects/Shields/shields.yml
Labels: S: Untriaged, Changes: No C#, size/S

#6 Coversbothears
  Content.Server/_Goobstation/CoversBothEars/CoversBothEarsSystem.cs
  Content.Shared/_Goobstation/CoversBothEars/CoversBothEarsComponent.cs
Labels: S: Untriaged, size/S
